version: "0.5"

processes:
  backend:
    command: make backend/run
    depends_on:
      postgresql:
        condition: "process_started"

  webapp:
    command: pnpm dev
    depends_on:
      backend:
        condition: "process_started"
    availability:
      restart: "always"

  postgresql:
    command: |
      if [ ! -d "$POSTGRESQL_DATA_DIR" ]; then
        mkdir -p $POSTGRESQL_DATA_DIR
      fi
      if [ -z "$(ls -A $POSTGRESQL_DATA_DIR)" ]; then
        initdb -D $POSTGRESQL_DATA_DIR
      fi

      pg_ctl -D $POSTGRESQL_DATA_DIR -o "-p $POSTGRESQL_PORT -k $POSTGRESQL_UNIX_PORT" -l $POSTGRESQL_HOME/postgresql.log start && echo 'Starting PostgreSQL... check postgresql_logs for details'
    is_daemon: true
    shutdown:
      command: "pg_ctl -D $POSTGRESQL_DATA_DIR stop"
    availability:
      restart: "always"
    depends_on:
      postgresql_logs:
        condition: "process_started"

  postgresql_logs:
    command: "tail -f $POSTGRESQL_HOME/postgresql.log"
    availability:
      restart: "always"
