# https://f1bonacc1.github.io/process-compose/
version: "0.5"

processes:
  backend:
    command: make backend/run
    depends_on:
      postgresql:
        condition: "process_started"

  webapp:
    command: pnpm dev
    depends_on:
      backend:
        condition: "process_started"
    availability:
      restart: "always"

  postgresql:
    command: |
      if [ ! -d "$POSTGRESQL_DATA_DIR" ]; then
        mkdir $POSTGRESQL_DATA_DIR
      fi
      if [ -z "$(ls -A $POSTGRESQL_DATA_DIR)" ]; then
        postgresqld --datadir=$POSTGRESQL_DATA_DIR --initialize-insecure
      fi

      postgresqld --socket=$POSTGRESQL_UNIX_PORT --datadir=$POSTGRESQL_DATA_DIR --port=$POSTGRESQL_PORT --log-error=$POSTGRESQL_HOME/postgresql.log & POSTGRESQL_PID=$! && echo 'Starting postgresqld... check postgresql_logs for details'
    is_daemon: true
    shutdown:
      command: "postgresqladmin -u root shutdown"
    availability:
      restart: "always"
    depends_on:
      postgresql_logs:
        condition: "process_started"
  postgresql_logs:
    command: "tail -f $POSTGRESQL_HOME/postgresql.log"
    availability:
      restart: "always"
