// Package db_model contains generated code for schema 'habit'.
package db_model

// Code generated by xo. DO NOT EDIT.

// Comment represents a row from 'habit.comments'.
type Comment struct {
	ID          string `json:"id"`           // id
	PostID      string `json:"post_id"`      // post_id
	UserID      string `json:"user_id"`      // user_id
	CommentText string `json:"comment_text"` // comment_text
}
