package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"time"
)

// Habit represents a row from 'habit.habits'.
type Habit struct {
	ID           string         `json:"id"`            // id
	UserID       string         `json:"user_id"`       // user_id
	Name         string         `json:"name"`          // name
	Description  sql.NullString `json:"description"`   // description
	StartDate    time.Time      `json:"start_date"`    // start_date
	EndDate      sql.NullTime   `json:"end_date"`      // end_date
	ReminderTime sql.NullString `json:"reminder_time"` // reminder_time
}
