package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// Habit represents a row from 'habit.habits'.
type Habit struct {
	ID           string         `json:"id"`            // id
	UserID       string         `json:"user_id"`       // user_id
	Name         string         `json:"name"`          // name
	Description  sql.NullString `json:"description"`   // description
	ReminderTime sql.NullString `json:"reminder_time"` // reminder_time
}
