package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql/driver"
	"fmt"
)

// NotificationType is the 'notification_type' enum type from schema 'habit'.
type NotificationType uint16

// NotificationType values.
const (
	// NotificationTypeReaction is the 'reaction' notification_type.
	NotificationTypeReaction NotificationType = 1
	// NotificationTypeComment is the 'comment' notification_type.
	NotificationTypeComment NotificationType = 2
)

// String satisfies the [fmt.Stringer] interface.
func (nt NotificationType) String() string {
	switch nt {
	case NotificationTypeReaction:
		return "reaction"
	case NotificationTypeComment:
		return "comment"
	}
	return fmt.Sprintf("NotificationType(%d)", nt)
}

// MarshalText marshals [NotificationType] into text.
func (nt NotificationType) MarshalText() ([]byte, error) {
	return []byte(nt.String()), nil
}

// UnmarshalText unmarshals [NotificationType] from text.
func (nt *NotificationType) UnmarshalText(buf []byte) error {
	switch str := string(buf); str {
	case "reaction":
		*nt = NotificationTypeReaction
	case "comment":
		*nt = NotificationTypeComment
	default:
		return ErrInvalidNotificationType(str)
	}
	return nil
}

// Value satisfies the [driver.Valuer] interface.
func (nt NotificationType) Value() (driver.Value, error) {
	return nt.String(), nil
}

// Scan satisfies the [sql.Scanner] interface.
func (nt *NotificationType) Scan(v interface{}) error {
	switch x := v.(type) {
	case []byte:
		return nt.UnmarshalText(x)
	case string:
		return nt.UnmarshalText([]byte(x))
	}
	return ErrInvalidNotificationType(fmt.Sprintf("%T", v))
}

// NullNotificationType represents a null 'notification_type' enum for schema 'habit'.
type NullNotificationType struct {
	NotificationType NotificationType
	// Valid is true if [NotificationType] is not null.
	Valid bool
}

// Value satisfies the [driver.Valuer] interface.
func (nnt NullNotificationType) Value() (driver.Value, error) {
	if !nnt.Valid {
		return nil, nil
	}
	return nnt.NotificationType.Value()
}

// Scan satisfies the [sql.Scanner] interface.
func (nnt *NullNotificationType) Scan(v interface{}) error {
	if v == nil {
		nnt.NotificationType, nnt.Valid = 0, false
		return nil
	}
	err := nnt.NotificationType.Scan(v)
	nnt.Valid = err == nil
	return err
}

// ErrInvalidNotificationType is the invalid [NotificationType] error.
type ErrInvalidNotificationType string

// Error satisfies the error interface.
func (err ErrInvalidNotificationType) Error() string {
	return fmt.Sprintf("invalid NotificationType(%s)", string(err))
}
