package db_model

// Code generated by xo. DO NOT EDIT.

// Post represents a row from 'habit.posts'.
type Post struct {
	ID       string `json:"id"`        // id
	RecordID string `json:"record_id"` // record_id
	UserID   string `json:"user_id"`   // user_id
}
