package db_model

// Code generated by xo. DO NOT EDIT.

// Reaction represents a row from 'habit.reactions'.
type Reaction struct {
	ID     string `json:"id"`      // id
	PostID string `json:"post_id"` // post_id
	UserID string `json:"user_id"` // user_id
}
