package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
	"time"
)

// Record represents a row from 'habit.records'.
type Record struct {
	ID         string         `json:"id"`          // id
	HabitID    string         `json:"habit_id"`    // habit_id
	UserID     string         `json:"user_id"`     // user_id
	RecordDate time.Time      `json:"record_date"` // record_date
	Comment    sql.NullString `json:"comment"`     // comment
	PhotoURL   sql.NullString `json:"photo_url"`   // photo_url
}
