package db_model

// Code generated by xo. DO NOT EDIT.

import (
	"database/sql"
)

// User represents a row from 'habit.users'.
type User struct {
	ID              string         `json:"id"`                // id
	Username        string         `json:"username"`          // username
	ProfileImageURL sql.NullString `json:"profile_image_url"` // profile_image_url
	Bio             sql.NullString `json:"bio"`               // bio
}
